### ISSUE TITLE
Need suport for the action to scaffolding into the 

### ISSUE THREAD

**Issue by mexang10** [dotnet/AspNetCore.Docs.es-es#44]
[at the moment to add scaffolding, adding controller apis action to use entity framework 
match me an error aparetnly the next time need suport  to avisement 
![scaffolding error ](https://user-images.githubusercontent.com/55614502/76377473-99d94100-6310-11ea-8a0e-160901c208fc.jpg)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introducción a ASP.NET Core](https://docs.microsoft.com/es-mx/aspnet/core/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/index.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mexang10** [comment]
i try  much times  dont works

**Comment by srvbpigh** [comment]
Hello, @mexang10
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mexang10 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
