### ISSUE TITLE
Se traduce "Blazor" por "extraordinaria"

### ISSUE THREAD

**Issue by lestival** [dotnet/AspNetCore.Docs.es-es#45]
No se debe traducir la palabra "Blazor"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Introducción a ASP.NET Core Blazor](https://docs.microsoft.com/es-es/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio&utm_source=jeliknes&utm_medium=github&utm_campaign=blazor-wasm&WT.mc_id=blazorwasm-github-jeliknes&viewFallbackFrom=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@CeciAc The `no-loc` metadata is present on all of these topics.

**Comment by srvbpigh** [comment]
Hello, @lestival
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @lestival 

Gracias por su contribución.

Actualmente no se aceptan aportaciones relacionadas con problemas de traducción para el contenido de traducción automática.

Le agradecemos sus comentarios y sugerencias sobre el contenido traducido por personas, que se usa para entrenar los motores de traducción automática, por lo que, con el tiempo, sus contribuciones mejorarán la calidad tanto de la traducción automática como de la traducción humana.

Los temas traducidos por personas pueden distinguirse de los temas traducidos de forma automática por el valor “HT” de ms.translationtype en los metadatos (frente a “MT” para la traducción automática) en el encabezado de cada archivo de contenido.

Muchas gracias por su ayuda.

Equipo de experiencia global de Microsoft DOCS
