### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by rgrastur** [dotnet/AspNetCore.Docs.es-es#46]
I have an error in line 446 from qrcode.js

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Habilitar la generación de código QR para las aplicaciones de TOTP Authenticator en ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Open an issue at https://davidshimjs.github.io/qrcodejs/

Recommend closing this issue.

**Comment by srvbpigh** [comment]
Hello, @rgrastur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Rick-Anderson** [comment]
@srvbpigh  @CeciAc  see my comment. Recommend closing as that's not our code.
