### ISSUE TITLE
Readonly properties VS Constants

### ISSUE THREAD

**Issue by forteg24** [dotnet/AspNetCore.Docs.es-es#50]
Maybe is just cosmetic but I don't see the reason why you use readonly properties (Static) instead of public consts.
public static string Entry { get { return "_Entry"; } } VS public const string Entry = "_Entry";

Are not the constants created by things like that?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Almacenar en memoria caché en ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/performance/caching/memory?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @forteg24
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @forteg24:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/AspNetCore.Docs/issues/18150.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
