### ISSUE TITLE
Traducción automática

### ISSUE THREAD

**Issue by Bukran** [dotnet/AspNetCore.Docs.es-es#51]
Los números de versión aparecen separados por una coma como si se tratase de cifras. En este caso deberían aparecer con un punto.

Version numbers are written using comma separator as if they were figures. In this case, they should be dot-separated.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 76f39eec-9dd1-6167-56ec-47b26e0b5063
* Version Independent ID: f9f2b0f3-01eb-cf58-8767-194fe0fc0e44
* Content: [Migrar de ASP.NET Core 2,2 a 3,0](https://docs.microsoft.com/es-es/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/22-to-30.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/migration/22-to-30.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Bukran
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hello @Bukran :

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

cc @JasonCard
