### ISSUE TITLE
Mejorar página en español.

### ISSUE THREAD

**Issue by stojangb** [dotnet/AspNetCore.Docs.es-es#52]
Todo bien, lo único que me gustaría mejorar es al final de la página  en español dice:

"Para obtener instrucciones sobre la globalización, consulte esta cuestión en GitHub."

y el término "cuestión" es informal y esta mal utilizado, favor cambiar por una de estas frases:

"Para obtener instrucciones sobre la globalización, consulte este hilo en GitHub."

"Para obtener instrucciones sobre la globalización, consulte esta pregunta en GitHub."

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Parte 2. Adición de un modelo a una aplicación de Razor Pages en ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hola, @stojangb: 

Estamos cambiando nuestro proceso interno y la canalización de ingeniería. Lamentablemente, esto está dando lugar a retrasos en el procesamiento de los comentarios.

Agradecemos realmente su contribución a nuestros artículos y esperamos seguir contando con su apoyo y comprensión.

**Comment by vaqueraexe** [comment]
@srvbpigh Puedo trabajar en esta issue?

**Comment by Rick-Anderson** [comment]
@stojangb thanks for reporting this. It's not a good translation, but close enough. Your last suggestion is almost identical
