### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by wjvelasquez** [dotnet/AspNetCore.Docs.es-es#55]
Una persona que esta tratando de aprender lo nuevo y se consigue con tantos errores pierde el animo.
Por esas razones se pierde el animo y asi como yo muchisimos mas.

Esta pagina tiene varios errores y omisiones
Ejemplo de lo que no funciona en VS 2019 - v.16.7.2 (la mas reciente en este momento que escribo)

builder.Configuration.AddEFConfiguration(
            options => options.UseInMemoryDatabase("InMemoryDb"));

builder.Services.AddOidcAuthentication(options =>
             builder.Configuration.Bind("Local", options.ProviderOptions));

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: 7367a651-2b27-0a57-e7d0-95686cc97f1c
* Version Independent ID: 8c769648-728d-72ce-ebf6-2a06e5076aa2
* Content: [Configuración de Blazor en ASP.NET Core](https://docs.microsoft.com/es-mx/aspnet/core/blazor/fundamentals/configuration?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/configuration.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/blazor/fundamentals/configuration.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The code is correct. You're probably missing NuGet packages/includes.

@guardrex  let me know if I should reopen and xfer.
