### ISSUE TITLE
No funciona el boton Add todo

### ISSUE THREAD

**Issue by josesepulvedavelez** [dotnet/AspNetCore.Docs.es-es#58]
[tengo exactamente el codigo descrito en el presente tutorial, sin embargo no me funciona el boton add, no hace nada]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2b677fc7-67a6-ef2f-21ee-cdffddeaac66
* Version Independent ID: b84bbc11-059d-26d1-e693-2d34dbff4af5
* Content: [Creación de una aplicación de lista de tareas pendientes Blazor](https://docs.microsoft.com/es-es/aspnet/core/tutorials/build-a-blazor-app?view=aspnetcore-5.0)
* Content Source: [aspnetcore/tutorials/build-a-blazor-app.md](https://github.com/dotnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/tutorials/build-a-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hola @josesepulvedavelez ... Los problemas de no traducción deben abrirse desde la versión en inglés del artículo en inglés. Van al repositorio de documentación en inglés.

Sin embargo, para este error, no sé qué haría que el botón fallara. Vuelve sobre tus pasos y asegúrate de haber hecho todo.

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
